spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registrations
    username: your_db_username
    password: your_db_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
